import assert from 'node:assert/strict';
import { generatePostgresDdl } from '../postgresDdl';
import { SqlSchema } from '../sqlModel';

function emptySchema(overrides: Partial<SqlSchema> = {}): SqlSchema {
	return { enums: [], tables: [], indexes: [], foreignKeys: [], warnings: [], ...overrides };
}

describe('generatePostgresDdl', () => {
	it('wraps output in a transaction with a descriptive header', () => {
		const sql = generatePostgresDdl(emptySchema(), { sourcePath: 'prisma/schema.prisma' });
		assert.ok(sql.startsWith('-- PostgreSQL schema generated by Prisma Visualizer.'));
		assert.ok(sql.includes('-- Source: prisma/schema.prisma'));
		assert.ok(sql.includes('no table data'));
		assert.ok(sql.includes('BEGIN;'));
		assert.ok(sql.trimEnd().endsWith('COMMIT;'));
	});

	it('warns when the datasource targets a database other than postgres', () => {
		const sql = generatePostgresDdl(emptySchema({ provider: 'mysql' }));
		assert.ok(sql.includes('WARNING') && sql.includes('mysql'));
	});

	it('renders enums as CREATE TYPE with quoted values', () => {
		const sql = generatePostgresDdl(emptySchema({ enums: [{ name: 'Role', values: ['ADMIN', 'USER'] }] }));
		assert.ok(sql.includes(`CREATE TYPE "Role" AS ENUM ('ADMIN', 'USER');`));
	});

	it('renders columns with nullability, defaults and a primary key constraint', () => {
		const sql = generatePostgresDdl(
			emptySchema({
				tables: [
					{
						name: 'User',
						columns: [
							{ name: 'id', type: { sql: 'SERIAL', isArray: false }, isNullable: false, isSerial: true, warnings: [] },
							{ name: 'bio', type: { sql: 'TEXT', isArray: false }, isNullable: true, isSerial: false, warnings: [] },
							{
								name: 'active',
								type: { sql: 'BOOLEAN', isArray: false },
								isNullable: false,
								isSerial: false,
								default: { kind: 'expression', value: 'true' },
								warnings: [],
							},
							{
								name: 'title',
								type: { sql: 'TEXT', isArray: false },
								isNullable: false,
								isSerial: false,
								default: { kind: 'literal', value: "it's" },
								warnings: [],
							},
							{
								name: 'tags',
								type: { sql: 'TEXT', isArray: true },
								isNullable: true,
								isSerial: false,
								default: { kind: 'emptyArray' },
								warnings: [],
							},
						],
						primaryKey: { name: 'User_pkey', columns: ['id'] },
					},
				],
			}),
		);

		assert.ok(sql.includes('    "id" SERIAL NOT NULL,'));
		assert.ok(sql.includes('    "bio" TEXT,'));
		assert.ok(sql.includes('    "active" BOOLEAN NOT NULL DEFAULT true,'));
		assert.ok(sql.includes(`    "title" TEXT NOT NULL DEFAULT 'it''s',`), 'string defaults must escape single quotes');
		assert.ok(sql.includes('    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],'));
		assert.ok(sql.includes('    CONSTRAINT "User_pkey" PRIMARY KEY ("id")'));
	});

	it('does not put a trailing comma on the last column when there is no primary key', () => {
		const sql = generatePostgresDdl(
			emptySchema({
				tables: [
					{
						name: '_AToB',
						columns: [
							{ name: 'A', type: { sql: 'INTEGER', isArray: false }, isNullable: false, isSerial: false, warnings: [] },
							{ name: 'B', type: { sql: 'INTEGER', isArray: false }, isNullable: false, isSerial: false, warnings: [] },
						],
					},
				],
			}),
		);
		assert.ok(sql.includes('    "A" INTEGER NOT NULL,\n    "B" INTEGER NOT NULL\n);'));
	});

	it('emits column warnings as comments without breaking comma placement', () => {
		const sql = generatePostgresDdl(
			emptySchema({
				tables: [
					{
						name: 'T',
						columns: [
							{
								name: 'weird',
								type: { sql: 'ODDTYPE', isArray: false },
								isNullable: false,
								isSerial: false,
								warnings: ['Unrecognized native type'],
							},
						],
					},
				],
			}),
		);
		assert.ok(sql.includes('    -- WARNING: Unrecognized native type'));
		assert.ok(sql.includes('    "weird" ODDTYPE NOT NULL\n);'), 'the final column must not gain a comma from a following comment');
	});

	it('renders unique and plain indexes', () => {
		const sql = generatePostgresDdl(
			emptySchema({
				indexes: [
					{ name: 'User_email_key', table: 'User', columns: ['email'], isUnique: true },
					{ name: 'User_name_idx', table: 'User', columns: ['first', 'last'], isUnique: false },
				],
			}),
		);
		assert.ok(sql.includes('CREATE UNIQUE INDEX "User_email_key" ON "User"("email");'));
		assert.ok(sql.includes('CREATE INDEX "User_name_idx" ON "User"("first", "last");'));
	});

	it('renders foreign keys after tables so the file runs top to bottom', () => {
		const sql = generatePostgresDdl(
			emptySchema({
				tables: [{ name: 'Post', columns: [], primaryKey: undefined }],
				foreignKeys: [
					{
						name: 'Post_authorId_fkey',
						table: 'Post',
						columns: ['authorId'],
						referencedTable: 'User',
						referencedColumns: ['id'],
						onDelete: 'CASCADE',
						onUpdate: 'NO ACTION',
					},
				],
			}),
		);
		assert.ok(
			sql.includes(
				'ALTER TABLE "Post" ADD CONSTRAINT "Post_authorId_fkey" FOREIGN KEY ("authorId") ' +
					'REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE NO ACTION;',
			),
		);
		assert.ok(sql.indexOf('CREATE TABLE "Post"') < sql.indexOf('ALTER TABLE "Post"'));
	});

	it('escapes double quotes in identifiers', () => {
		const sql = generatePostgresDdl(
			emptySchema({ tables: [{ name: 'we"ird', columns: [], primaryKey: undefined }] }),
		);
		assert.ok(sql.includes('CREATE TABLE "we""ird"'));
	});
});
