import { SqlColumn, SqlDefault, SqlForeignKey, SqlIndex, SqlSchema, SqlTable } from './sqlModel';

export interface GenerateDdlOptions {
	/** Shown in the file header so the output is traceable back to its source. */
	sourcePath?: string;
}

function quote(identifier: string): string {
	return `"${identifier.replace(/"/g, '""')}"`;
}

function quoteAll(identifiers: string[]): string {
	return identifiers.map(quote).join(', ');
}

function sqlStringLiteral(value: string): string {
	return `'${value.replace(/'/g, "''")}'`;
}

function renderDefault(def: SqlDefault, columnSqlType: string): string {
	switch (def.kind) {
		case 'literal':
			return sqlStringLiteral(def.value);
		case 'expression':
			return def.value;
		case 'emptyArray':
			return `ARRAY[]::${columnSqlType}[]`;
	}
}

function renderColumn(column: SqlColumn): string[] {
	const lines = column.warnings.map((w) => `    -- WARNING: ${w}`);
	const type = `${column.type.sql}${column.type.isArray ? '[]' : ''}`;
	const parts = [`    ${quote(column.name)} ${type}`];
	parts.push(column.isNullable ? '' : ' NOT NULL');
	if (column.default) {
		parts.push(` DEFAULT ${renderDefault(column.default, column.type.sql)}`);
	}
	lines.push(parts.join(''));
	return lines;
}

function renderTable(table: SqlTable): string {
	const body: string[] = [];
	for (const column of table.columns) {
		body.push(...renderColumn(column));
	}
	if (table.primaryKey) {
		body.push(`    CONSTRAINT ${quote(table.primaryKey.name)} PRIMARY KEY (${quoteAll(table.primaryKey.columns)})`);
	}

	// Only the value-bearing lines take a trailing comma; comment lines must not.
	const rendered = body.map((line, i) => {
		const isComment = line.trimStart().startsWith('--');
		const isLastValue = body.slice(i + 1).every((l) => l.trimStart().startsWith('--'));
		return isComment || isLastValue ? line : `${line},`;
	});

	return `CREATE TABLE ${quote(table.name)} (\n${rendered.join('\n')}\n);`;
}

function renderIndex(index: SqlIndex): string {
	const kind = index.isUnique ? 'CREATE UNIQUE INDEX' : 'CREATE INDEX';
	return `${kind} ${quote(index.name)} ON ${quote(index.table)}(${quoteAll(index.columns)});`;
}

function renderForeignKey(fk: SqlForeignKey): string {
	return (
		`ALTER TABLE ${quote(fk.table)} ADD CONSTRAINT ${quote(fk.name)} ` +
		`FOREIGN KEY (${quoteAll(fk.columns)}) REFERENCES ${quote(fk.referencedTable)}(${quoteAll(fk.referencedColumns)}) ` +
		`ON DELETE ${fk.onDelete} ON UPDATE ${fk.onUpdate};`
	);
}

/**
 * Emits PostgreSQL DDL for a schema. Statement order (enums -> tables -> indexes -> foreign keys)
 * lets the file run top to bottom: deferring every foreign key to the end means tables never need
 * to be topologically sorted, and circular references work without special handling.
 */
export function generatePostgresDdl(schema: SqlSchema, options: GenerateDdlOptions = {}): string {
	const sections: string[] = [];

	const header = ['-- PostgreSQL schema generated by Prisma Visualizer.'];
	if (options.sourcePath) {
		header.push(`-- Source: ${options.sourcePath}`);
	}
	header.push('-- Structure only — this file contains no table data.');
	if (schema.provider && schema.provider !== 'postgresql') {
		header.push(`-- WARNING: the datasource provider is "${schema.provider}", not "postgresql"; review before applying.`);
	}
	for (const warning of schema.warnings) {
		header.push(`-- WARNING: ${warning}`);
	}
	sections.push(header.join('\n'));

	sections.push('BEGIN;');

	for (const e of schema.enums) {
		sections.push(`CREATE TYPE ${quote(e.name)} AS ENUM (${e.values.map(sqlStringLiteral).join(', ')});`);
	}

	for (const table of schema.tables) {
		sections.push(renderTable(table));
	}

	for (const index of schema.indexes) {
		sections.push(renderIndex(index));
	}

	for (const fk of schema.foreignKeys) {
		sections.push(renderForeignKey(fk));
	}

	sections.push('COMMIT;');

	return `${sections.join('\n\n')}\n`;
}
